# Generated by Django 4.2 on 2023-12-23 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vaccine_calendar", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={
                "verbose_name": "объект расписания",
                "verbose_name_plural": "объекты расписания",
            },
        ),
    ]
