# Generated by Django 4.2 on 2023-12-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="название города"
                    ),
                ),
            ],
            options={
                "verbose_name": "город",
                "verbose_name_plural": "города",
            },
        ),
    ]
