# Generated by Django 4.2 on 2023-12-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="название клиники",
                        max_length=256,
                        verbose_name="клиника",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="город/населенный пункт, в котором находится клиника",
                        max_length=128,
                        verbose_name="место",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="адрес, где находится клиника",
                        max_length=128,
                        verbose_name="адрес",
                    ),
                ),
                (
                    "lisense",
                    models.CharField(
                        help_text="лицензия на медицинскую деятельность",
                        max_length=256,
                        verbose_name="лицензия",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="номер телефона для связи с администратором клиники",
                        max_length=12,
                        verbose_name="номер телефона",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GT", "получено"),
                            ("PR", "в обработке"),
                            ("OK", "ответ дан"),
                        ],
                        default="GT",
                        help_text="статус обработки формы",
                        max_length=2,
                        verbose_name="статус обработки",
                    ),
                ),
                (
                    "clinic_mail",
                    models.EmailField(
                        help_text="электронная почта клиники",
                        max_length=254,
                        verbose_name="почта",
                    ),
                ),
            ],
            options={
                "verbose_name": "клиника",
                "verbose_name_plural": "клиники",
            },
        ),
    ]
