# Generated by Django 4.2 on 2023-12-21 20:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Главное изображение поликлиники",
                        null=True,
                        upload_to="catalog/%Y/%m/%d/",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название клиники",
                        max_length=256,
                        verbose_name="клиника",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Адрес, где находится клиника",
                        max_length=128,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                15, message="Слишком короткий текст."
                            )
                        ],
                        verbose_name="адрес",
                    ),
                ),
                (
                    "lisense",
                    models.CharField(
                        help_text="Лицензия на медицинскую деятельность",
                        max_length=256,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                10, message="Слишком короткий текст."
                            )
                        ],
                        verbose_name="лицензия",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        error_messages={
                            "invalid": "Пожалуйста, введите корректный номер телефона."
                        },
                        help_text="Номер телефона для связи с администратором клиники",
                        max_length=128,
                        region="RU",
                        verbose_name="номер телефона",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GT", "получено"),
                            ("PR", "в обработке"),
                            ("OK", "ответ дан"),
                        ],
                        default="GT",
                        help_text="Статус обработки формы",
                        max_length=2,
                        verbose_name="статус обработки",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False,
                        help_text="Одобрена поликлиника для работы на сайте или нет",
                        verbose_name="одобрено",
                    ),
                ),
                (
                    "clinic_mail",
                    models.EmailField(
                        help_text="Электронная почта клиники",
                        max_length=254,
                        verbose_name="почта",
                    ),
                ),
                (
                    "private",
                    models.CharField(
                        choices=[("PR", "частная"), ("ST", "государственная")],
                        default="ST",
                        help_text="Частная или приватная клиника",
                        max_length=2,
                        verbose_name="частная или приватная",
                    ),
                ),
            ],
            options={
                "verbose_name": "клиника",
                "verbose_name_plural": "клиники",
            },
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="когда был создан лог",
                        verbose_name="лог",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        db_column="from",
                        help_text="из какого статуса перешла заявка",
                        max_length=2,
                        verbose_name="начальное состояние",
                    ),
                ),
                (
                    "to",
                    models.CharField(
                        help_text="в какой статус перешла заявка",
                        max_length=2,
                        verbose_name="новое состояние",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        help_text="заявка, в которой поменялся статус",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinics.clinics",
                        verbose_name="заявка",
                    ),
                ),
            ],
            options={
                "verbose_name": "лог статусов",
                "verbose_name_plural": "логи статусов",
            },
        ),
    ]
