# Generated by Django 4.2 on 2023-12-08 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания"
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        db_column="from",
                        help_text="из какого статуса перешла заявка",
                        max_length=2,
                        verbose_name="начальное состояние",
                    ),
                ),
                (
                    "to",
                    models.CharField(
                        help_text="в какой статус перешла заявка",
                        max_length=2,
                        verbose_name="новое состояние",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        help_text="заявка, в которой поменялся статус",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        related_query_name="feedback",
                        to="clinics.clinics",
                        verbose_name="заявка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="пользователь, который изменил статус",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        related_query_name="user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "лог статусов",
                "verbose_name_plural": "логи статусов",
            },
        ),
    ]
