# Generated by Django 4.2 on 2023-12-21 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinics", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuslog",
            name="user",
            field=models.ForeignKey(
                help_text="пользователь, который изменил статус",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                related_query_name="user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AddField(
            model_name="clinics",
            name="admin",
            field=models.ForeignKey(
                default=None,
                help_text="Администратор клиники, который будет работать в профиле",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin",
                to=settings.AUTH_USER_MODEL,
                verbose_name="администратор",
            ),
        ),
        migrations.AddField(
            model_name="clinics",
            name="city",
            field=models.ForeignKey(
                default=613,
                help_text="город/населенный пункт, в котором находится клиника",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.city",
                verbose_name="город",
            ),
        ),
    ]
