# Generated by Django 4.2 on 2023-12-10 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinics", "0002_statuslog"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinics",
            name="admin",
            field=models.ForeignKey(
                default=1,
                help_text="администратор клиники, который будет работать в профиле",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="администратор",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="clinic",
            field=models.ForeignKey(
                help_text="заявка, в которой поменялся статус",
                on_delete=django.db.models.deletion.CASCADE,
                to="clinics.clinics",
                verbose_name="заявка",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="когда был создан лог",
                verbose_name="лог",
            ),
        ),
    ]
