# Generated by Django 4.2 on 2023-12-22 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinics", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuslog",
            name="user",
            field=models.ForeignKey(
                help_text="пользователь, который изменил статус",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
