# Generated by Django 4.2 on 2023-12-09 08:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinics", "0002_statuslog"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinics",
            name="admin",
            field=models.ForeignKey(
                default=1,
                help_text="Администратор клиники, который будет работать в профиле",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="администратор",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clinics",
            name="address",
            field=models.CharField(
                help_text="Адрес, где находится клиника",
                max_length=128,
                validators=[
                    django.core.validators.MinLengthValidator(
                        15, message="Слишком короткий текст."
                    )
                ],
                verbose_name="адрес",
            ),
        ),
        migrations.AlterField(
            model_name="clinics",
            name="city",
            field=models.CharField(
                help_text="Город/населенный пункт, в котором находится клиника",
                max_length=128,
                verbose_name="место",
            ),
        ),
        migrations.AlterField(
            model_name="clinics",
            name="clinic_mail",
            field=models.EmailField(
                help_text="Электронная почта клиники",
                max_length=254,
                verbose_name="почта",
            ),
        ),
        migrations.AlterField(
            model_name="clinics",
            name="lisense",
            field=models.CharField(
                help_text="Лицензия на медицинскую деятельность",
                max_length=256,
                validators=[
                    django.core.validators.MinLengthValidator(
                        10, message="Слишком короткий текст."
                    )
                ],
                verbose_name="лицензия",
            ),
        ),
        migrations.AlterField(
            model_name="clinics",
            name="name",
            field=models.CharField(
                help_text="Название клиники",
                max_length=256,
                verbose_name="клиника",
            ),
        ),
        migrations.AlterField(
            model_name="clinics",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                error_messages={
                    "invalid": "Пожалуйста, введите корректный номер телефона."
                },
                help_text="Номер телефона для связи с администратором клиники",
                max_length=128,
                region="RU",
                verbose_name="номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="clinic",
            field=models.ForeignKey(
                help_text="заявка, в которой поменялся статус",
                on_delete=django.db.models.deletion.CASCADE,
                to="clinics.clinics",
                verbose_name="заявка",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="когда был создан лог",
                verbose_name="лог",
            ),
        ),
    ]
