# Generated by Django 4.2 on 2023-12-13 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinics", "0003_clinics_admin_alter_statuslog_clinic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinics",
            name="admin",
        ),
        migrations.AddField(
            model_name="clinics",
            name="admins",
            field=models.ManyToManyField(
                help_text="администраторs клиники",
                to=settings.AUTH_USER_MODEL,
                verbose_name="администраторы",
            ),
        ),
    ]
