# Generated by Django 4.2 on 2023-12-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0003_clinics_admin_alter_clinics_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinics",
            name="approved",
            field=models.BooleanField(
                default=False,
                help_text="одобрена поликлиника для работы на сайте или нет",
                verbose_name="одобрено",
            ),
        ),
    ]
