# Generated by Django 4.2 on 2023-12-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0003_clinics_admin_alter_clinics_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinics",
            name="approved",
            field=models.BooleanField(
                default=False,
                help_text="одобрена поликлиника для работы на сайте или нет",
                verbose_name="одобрено",
            ),
        ),
        migrations.AddField(
            model_name="clinics",
            name="image",
            field=models.ImageField(
                help_text="главное изображение поликлиники",
                null=True,
                upload_to="catalog/%Y/%m/%d/",
                verbose_name="изображение",
            ),
        ),
    ]
