# Generated by Django 4.2 on 2023-12-23 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0003_alter_statuslog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinics",
            name="lisense",
            field=models.CharField(
                help_text="Лицензия на медицинскую деятельность",
                max_length=256,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        10, message="Слишком короткий текст."
                    )
                ],
                verbose_name="лицензия",
            ),
        ),
    ]
