# Generated by Django 4.2 on 2023-12-21 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0005_alter_clinics_city"),
        ("clinics", "0005_clinics_private_alter_clinics_approved_and_more"),
    ]

    operations = []
