# Generated by Django 4.2 on 2023-12-21 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinics", "0006_merge_20231221_1624"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinics",
            name="admins",
        ),
        migrations.AddField(
            model_name="clinics",
            name="admin",
            field=models.ForeignKey(
                default=1,
                help_text="Администратор клиники, который будет работать в профиле",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="администратор",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clinics",
            name="private",
            field=models.CharField(
                choices=[("PR", "частная"), ("ST", "государственная")],
                default="ST",
                help_text="Частная или приватная клиника",
                max_length=2,
                verbose_name="частная или приватная",
            ),
        ),
    ]
