# Generated by Django 4.2 on 2023-12-21 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinics", "0007_remove_clinics_admins_clinics_admin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinics",
            name="admin",
            field=models.ForeignKey(
                default=None,
                help_text="Администратор клиники, который будет работать в профиле",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="администратор",
            ),
        ),
    ]
