# Generated by Django 4.2 on 2023-12-21 20:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0008_alter_clinics_city"),
        ("clinics", "0009_alter_clinics_city"),
    ]

    operations = []
