# Generated by Django 4.2 on 2023-12-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("M", "мужской"), ("F", "женский")],
                max_length=1,
                verbose_name="пол",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="отчество"
            ),
        ),
    ]
