# Generated by Django 4.2 on 2023-12-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0003_clinics_admin_alter_statuslog_clinic_and_more"),
        ("users", "0002_alter_customuser_gender_alter_customuser_middle_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                help_text="клиника, к которой прикреплен пользователь",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clinics.clinics",
                verbose_name="клиника",
            ),
        ),
    ]
