# Generated by Django 4.2 on 2023-12-10 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0003_clinics_admin_alter_statuslog_clinic_and_more"),
        ("users", "0003_customuser_clinic"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="featured_clinics",
            field=models.ManyToManyField(
                help_text="клиники, которые выбрал пользователь для отслеживания",
                related_name="featured_clinics",
                to="clinics.clinics",
                verbose_name="отслеживаемые клиники",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                help_text="клиника, к которой прикреплен пользователь",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinic",
                to="clinics.clinics",
                verbose_name="клиника",
            ),
        ),
    ]
