# Generated by Django 4.2 on 2023-12-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_customuser_featured_clinics_alter_customuser_clinic"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_clinic_admin",
            field=models.BooleanField(
                default=False,
                help_text="является ли этот пользователь администратором клиники",
                verbose_name="администратор клиники",
            ),
        ),
    ]
