# Generated by Django 4.2 on 2023-12-13 16:03

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_customuser_featured_clinics_alter_customuser_clinic"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_clinic_admin",
            field=models.BooleanField(
                default=False,
                help_text="является ли этот пользователь администратором клиники",
                verbose_name="администратор клиники",
            ),
        ),
    ]
