# Generated by Django 4.2 on 2023-12-20 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.ForeignKey(
                default=1,
                help_text="город проживания пользователя",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.city",
                verbose_name="город",
            ),
            preserve_default=False,
        ),
    ]
