# Generated by Django 4.2 on 2023-12-20 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_customuser_city"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "город", "verbose_name_plural": "города"},
        ),
    ]
