# Generated by Django 4.2 on 2023-12-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("clinics", "0007_remove_clinics_admins_clinics_admin_and_more"),
        ("users", "0009_alter_customuser_city_delete_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_clinic_admin",
        ),
        migrations.AddField(
            model_name="customuser",
            name="admins_clinic",
            field=models.ForeignKey(
                blank=True,
                help_text="клиника, которой администрирует пользователь",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clinics.clinics",
                verbose_name="администрируемая клиника",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="city",
            field=models.ForeignKey(
                default=613,
                help_text="город проживания пользователя",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.city",
                verbose_name="город",
            ),
        ),
    ]
