# Generated by Django 4.2 on 2023-12-21 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("users", "0009_alter_customuser_city_delete_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="city",
            field=models.ForeignKey(
                default=613,
                help_text="город проживания пользователя",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.city",
                verbose_name="город",
            ),
        ),
    ]
