# Generated by Django 4.2 on 2023-12-21 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0007_remove_clinics_admins_clinics_admin_and_more"),
        ("users", "0010_remove_customuser_is_clinic_admin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="admins_clinic",
            field=models.ForeignKey(
                blank=True,
                help_text="клиника, которой администрирует пользователь",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admins_clinic",
                to="clinics.clinics",
                verbose_name="администрируемая клиника",
            ),
        ),
    ]
