# Generated by Django 4.2 on 2023-12-07 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VaccineCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="название болезни",
                        max_length=100,
                        verbose_name="болезнь",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="описание болезни", verbose_name="описание"
                    ),
                ),
                (
                    "num_of_vaccines",
                    models.PositiveIntegerField(
                        help_text="общее количество разработанных вакцин от этой болезни",
                        verbose_name="количество вакцин",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vaccines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="название вакцины, производство",
                        max_length=150,
                        verbose_name="вакцина",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="категория вакцины - название болезни, от которой она предназначена",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vaccines.vaccinecategories",
                        verbose_name="категория",
                    ),
                ),
            ],
        ),
    ]
