# Generated by Django 4.2 on 2023-12-21 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VaccineCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="название болезни",
                        max_length=100,
                        verbose_name="болезнь",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="описание болезни",
                        verbose_name="описание",
                    ),
                ),
                (
                    "num_of_vaccines",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="общее количество разработанных вакцин от этой болезни",
                        verbose_name="количество вакцин",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Vaccines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="название вакцины, производство",
                        max_length=150,
                        verbose_name="вакцина",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="категория вакцины - название болезни, от которой она предназначена",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vaccines.vaccinecategories",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "вакцина",
                "verbose_name_plural": "вакцины",
            },
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        help_text="поликлинка, в которой находится вакцина",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinics.clinics",
                        verbose_name="клиника",
                    ),
                ),
                (
                    "vaccines",
                    models.ForeignKey(
                        help_text="название имеющейся вакцины в поликлинике",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vaccines.vaccines",
                        verbose_name="вакцина",
                    ),
                ),
            ],
            options={
                "verbose_name": "наличие",
                "verbose_name_plural": "Наличия",
            },
        ),
    ]
