# Generated by Django 4.2 on 2023-12-23 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vaccines", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="availability",
            options={
                "verbose_name": "наличие",
                "verbose_name_plural": "наличия",
            },
        ),
    ]
