# Generated by Django 4.2 on 2023-12-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vaccines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccinecategories",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="описание болезни",
                verbose_name="описание",
            ),
        ),
        migrations.AlterField(
            model_name="vaccinecategories",
            name="num_of_vaccines",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="общее количество разработанных вакцин от этой болезни",
                verbose_name="количество вакцин",
            ),
        ),
        migrations.AlterField(
            model_name="vaccines",
            name="category",
            field=models.ForeignKey(
                help_text="категория вакцины - название болезни, от которой она предназначена",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vaccines.vaccinecategories",
                verbose_name="категория",
            ),
        ),
    ]
