# Generated by Django 4.2 on 2023-12-08 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vaccines", "0002_alter_vaccinecategories_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vaccinecategories",
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.AlterModelOptions(
            name="vaccines",
            options={
                "verbose_name": "вакцина",
                "verbose_name_plural": "вакцины",
            },
        ),
    ]
