# Generated by Django 4.2 on 2023-12-09 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vaccines", "0002_alter_vaccinecategories_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vaccinecategories",
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.AlterModelOptions(
            name="vaccines",
            options={
                "verbose_name": "вакцина",
                "verbose_name_plural": "вакцины",
            },
        ),
        migrations.AlterField(
            model_name="vaccines",
            name="category",
            field=models.ForeignKey(
                default=1,
                help_text="категория вакцины - название болезни, от которой она предназначена",
                on_delete=django.db.models.deletion.CASCADE,
                to="vaccines.vaccinecategories",
                verbose_name="категория",
            ),
            preserve_default=False,
        ),
    ]
