# Generated by Django 4.2 on 2023-12-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vaccines", "0002_alter_availability_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccinecategories",
            name="name",
            field=models.CharField(
                help_text="название болезни",
                max_length=100,
                unique=True,
                verbose_name="болезнь",
            ),
        ),
    ]
