# Generated by Django 4.2 on 2023-12-19 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0005_clinics_private_alter_clinics_approved_and_more"),
        ("vaccines", "0003_alter_vaccinecategories_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        help_text="поликлинка, в которой находится вакцина",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinics.clinics",
                        verbose_name="вакцина",
                    ),
                ),
                (
                    "vaccines",
                    models.ForeignKey(
                        help_text="название имеющейся вакцины в поликлинике",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vaccines.vaccines",
                        verbose_name="вакцина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Наличие",
                "verbose_name_plural": "Наличия",
            },
        ),
    ]
