# Generated by Django 4.2 on 2023-12-18 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0003_clinics_admin_alter_statuslog_clinic_and_more"),
        ("vaccines", "0003_alter_vaccinecategories_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Availiability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_free", models.BooleanField(verbose_name="бесплатность")),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinics.clinics",
                        verbose_name="клиника",
                    ),
                ),
                (
                    "illness",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vaccines.vaccinecategories",
                        verbose_name="заболевание",
                    ),
                ),
            ],
        ),
    ]
