# Generated by Django 4.2 on 2023-12-21 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vaccines", "0003_alter_vaccinecategories_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="availability",
            old_name="vaccine",
            new_name="vaccines",
        ),
    ]
