# Generated by Django 4.2 on 2023-12-23 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vaccines", "0003_remove_vaccinecategories_num_of_vaccines_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vaccinecategories",
            name="num_of_vaccines",
        ),
    ]
