# Generated by Django 4.2 on 2023-12-18 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0003_clinics_admin_alter_statuslog_clinic_and_more"),
        ("vaccines", "0004_availiability"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Availiability",
            new_name="Availability",
        ),
        migrations.AlterModelOptions(
            name="availability",
            options={
                "verbose_name": "Наличие",
                "verbose_name_plural": "Наличия",
            },
        ),
    ]
