# Generated by Django 4.2 on 2023-12-19 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vaccines", "0005_rename_availiability_availability_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availability",
            name="is_free",
        ),
    ]
