# Generated by Django 4.2 on 2023-12-19 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0003_clinics_admin_alter_statuslog_clinic_and_more"),
        ("vaccines", "0006_remove_availability_is_free"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availability",
            name="illness",
        ),
        migrations.AddField(
            model_name="availability",
            name="vaccine",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vaccines.vaccines",
                verbose_name="заболевание",
            ),
        ),
        migrations.AlterField(
            model_name="availability",
            name="clinic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clinics.clinics",
                verbose_name="клиника",
            ),
        ),
    ]
