# Generated by Django 4.2 on 2023-12-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "vaccines",
            "0007_remove_availability_illness_availability_vaccine_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="availability",
            name="vaccine",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vaccines.vaccines",
                verbose_name="вакцина",
            ),
        ),
    ]
