# Generated by Django 4.2 on 2023-12-21 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vaccines", "0008_alter_availability_vaccine"),
    ]

    operations = [
        migrations.RenameField(
            model_name="availability",
            old_name="vaccine",
            new_name="vaccines",
        ),
    ]
